// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_VisibilityRange","status":true,"description":"Use an image to display a visibility range image around the player's position","parameters":{"Zoom Variable":"3","Opacity Variable":"4","Z Position":"10"}}
];
