// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_CursorImage","status":true,"description":"(v.1.7) Display an animated image next to the selected menu command.","parameters":{"Cursor Image":"WindowCursor","Image Frames":"4","Position Centered":"true","Position Offset":"0,0","Animation Speed":"6","Command Indent":"20","Item Indent":"20","Start Hidden":"false"}}
];
